# Generated by Django 5.2 on 2025-05-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tiltle_recentwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams')], default='ML', max_length=2),
        ),
    ]
